### ISSUE TITLE
immune converter

### ISSUE THREAD

**Issue by quattrinia** [smussmann82/file_converters#2]
hi there,

I used the pyradstr to immanc converter. It produced a file but also spit out this error "Use of uninitialized value in concatenation (.) or string at /scratch/nmnh_corals/scripts/pyradStr2immanc.pl line 117.".  Any idea what this is? My str file at line 117 seems ok to me.
Thanks
Andrea

**Comment by stevemussmann** [comment]
Hi Andrea,

'line 117' is referring to the position in the pyradStr2immanc.pl script where the error was detected. This is where the script is supposed to be printing out the new immanc file. My guess is this probably means the script couldn't read something correctly from your input file.

I think different pyrad versions now write out slightly different formats of a Structure file; one of which might not be entirely compatible with my conversion script. This is a common issue since the Structure file format is so flexible.

If you're able to send me the files you input into the script (i.e., your structure file and population map) I should be able to figure out what is causing the problem. If you don't want to post them here, my email is smussmann at gmail.

-Steve

**Comment by quattrinia** [comment]
Thanks for the reply! I figured out the issue. A missing specimen in the map file~
Andrea

**Comment by stevemussmann** [comment]
Glad you figured it out. I'm going to close this issue but feel free to reopen or submit a new one if you run into other problems.  Thanks,

-Steve
